services:
  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private-net

  odoo:
    image: odoo:17
    container_name: odoo
    restart: unless-stopped
    depends_on:
      - db
    command: --limit-time-real=600 --limit-time-cpu=600
    env_file:
      - .env
    environment:
      HOST: ${ODOO_DB_HOST}
      PORT: ${ODOO_DB_PORT}
      USER: ${ODOO_DB_USER}
      PASSWORD: ${ODOO_DB_PASSWORD}
    ports:
      - "8069:8069"
    volumes:
      - odoo-filestore:/var/lib/odoo
    networks:
       private-net:
        aliases:
          - odoo
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - odoo
    ports:
      - "80:80"
    volumes:
      - ./nginx/odoo.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - private-net
volumes:
  postgres-data:
  odoo-filestore:

networks:
  private-net:
    driver: bridge
